import { AgentService } from '../services/agentService';
import type { ResearchRequest } from '../shared/types';
import { join } from 'path';
import { writeFile, mkdir } from 'fs/promises';

export class AgentManager {
  private projectRoot: string;
  private agent: AgentService;
  private onOutput?: (type: 'stdout' | 'stderr', data: string) => void;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
    this.agent = new AgentService();
  }

  setOutputHandler(handler: (type: 'stdout' | 'stderr', data: string) => void) {
    this.onOutput = handler;
  }

  private logOutput(message: string) {
    if (this.onOutput) {
      this.onOutput('stdout', message + '\n');
    }
  }

  async runResearch(request: ResearchRequest): Promise<string> {
    try {
      const result = await this.agent.research(
        {
          companyName: request.companyName || request.ticker,
          ticker: request.ticker
        },
        (message) => this.logOutput(message)
      );

      // Clean up result - remove any leading asterisks or markdown artifacts
      const cleanResult = result.replace(/^\*+/, '').trim();
      
      // Generate output filename with timestamp
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
      const outputFile = `research-${request.ticker}-${timestamp}.md`;
      const reportsDir = join(this.projectRoot, 'reports');
      
      // Ensure reports directory exists
      await mkdir(reportsDir, { recursive: true });
      
      const fullPath = join(reportsDir, outputFile);
      
      // Prepare the full report
      const reportType = 'Research Report';
      const fullReport = [
        `# ${reportType}`,
        `**Company:** ${request.companyName || request.ticker}`,
        `**Ticker:** ${request.ticker}`,
        `**Date:** ${new Date().toLocaleString()}`,
        '',
        '---',
        '',
        cleanResult,
        '',
        '---',
        `*Generated by Family Office Research Agent*`
      ].join('\n');
      
      // Write to file
      await writeFile(fullPath, fullReport);
      
      this.logOutput(`✅ ${reportType} saved to: ${outputFile}`);
      
      return fullPath;
    } catch (error) {
      const errorMsg = `Research failed: ${error instanceof Error ? error.message : 'Unknown error'}`;
      this.logOutput(errorMsg);
      throw new Error(errorMsg);
    }
  }

  async runReevaluate(request: ResearchRequest, existingReportPath: string): Promise<string> {
    try {
      // Read the existing report
      const fs = await import('fs/promises');
      const reportContent = await fs.readFile(existingReportPath, 'utf-8');
      
      const result = await this.agent.reevaluate(
        {
          companyName: request.companyName || request.ticker,
          ticker: request.ticker
        },
        reportContent,
        (message) => this.logOutput(message)
      );

      // Clean up result - remove any leading asterisks or markdown artifacts
      const cleanResult = result.replace(/^\*+/, '').trim();
      
      // Generate output filename with timestamp
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
      const outputFile = `research-${request.ticker}-${timestamp}.md`;
      const reportsDir = join(this.projectRoot, 'reports');
      
      // Ensure reports directory exists
      await mkdir(reportsDir, { recursive: true });
      
      const fullPath = join(reportsDir, outputFile);
      
      // Prepare the full report
      const fullReport = [
        '# Reevaluation Report',
        `**Company:** ${request.companyName || request.ticker}`,
        `**Ticker:** ${request.ticker}`,
        `**Date:** ${new Date().toLocaleString()}`,
        `**Original Report:** ${existingReportPath}`,
        '',
        '---',
        '',
        cleanResult,
        '',
        '---',
        `*Generated by Family Office Research Agent*`,
        `*Reevaluation of existing report*`
      ].join('\n');
      
      // Write to file
      await writeFile(fullPath, fullReport);
      
      this.logOutput(`✅ Reevaluation report saved to: ${outputFile}`);
      
      return fullPath;
    } catch (error) {
      const errorMsg = `Reevaluation failed: ${error instanceof Error ? error.message : 'Unknown error'}`;
      this.logOutput(errorMsg);
      throw new Error(errorMsg);
    }
  }

  async runChat(ticker: string, message: string, reportPath?: string, onStream?: (text: string) => void): Promise<string> {
    try {
      let reportContent: string | undefined;
      
      if (reportPath) {
        try {
          const fs = await import('fs/promises');
          reportContent = await fs.readFile(reportPath, 'utf-8');
          this.logOutput(`📄 Loaded report: ${reportPath}`);
        } catch (error) {
          this.logOutput(`❌ Error loading report: ${error instanceof Error ? error.message : 'Unknown error'}`);
        }
      }

      const result = await this.agent.chat(
        ticker,
        message,
        reportContent,
        (message) => this.logOutput(message),
        onStream
      );

      return result;
    } catch (error) {
      const errorMsg = `Chat failed: ${error instanceof Error ? error.message : 'Unknown error'}`;
      this.logOutput(errorMsg);
      throw new Error(errorMsg);
    }
  }

  async updateReport(ticker: string): Promise<string> {
    try {
      const result = await this.agent.updateReport(
        ticker,
        (message) => this.logOutput(message)
      );

      // Clean up result - remove any leading asterisks or markdown artifacts
      const cleanResult = result.replace(/^\*+/, '').trim();
      
      // Generate output filename with timestamp
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
      const outputFile = `research-${ticker}-${timestamp}.md`;
      const reportsDir = join(this.projectRoot, 'reports');
      
      // Ensure reports directory exists
      await mkdir(reportsDir, { recursive: true });
      
      const fullPath = join(reportsDir, outputFile);
      
      // Prepare the full report
      const fullReport = [
        '# Research Report',
        `**Company:** ${ticker}`,
        `**Ticker:** ${ticker}`,
        `**Date:** ${new Date().toLocaleString()}`,
        `**Updated:** ${new Date().toLocaleString()}`,
        '',
        '---',
        '',
        cleanResult,
        '',
        '---',
        `*Generated by Family Office Research Agent*`,
        `*Updated during chat session*`
      ].join('\n');
      
      // Write to file
      await writeFile(fullPath, fullReport);
      
      this.logOutput(`✅ Updated report saved to: ${outputFile}`);
      
      return fullPath;
    } catch (error) {
      const errorMsg = `Report update failed: ${error instanceof Error ? error.message : 'Unknown error'}`;
      this.logOutput(errorMsg);
      throw new Error(errorMsg);
    }
  }

  async cleanup(): Promise<void> {
    await this.agent.cleanup();
  }
}
